cdef extern from "difmap_api.h":
    # Getters
    int get_native_no_error()
    int get_native_map_nx()
    int get_native_map_ny()
    char* get_native_source_name()
    float* get_native_map_data()
    float* get_native_beam_data()
    double get_native_bmaj()
    double get_native_bmin()
    double get_native_bpa()
    double get_native_estimated_bmaj()
    double get_native_estimated_bmin()
    double get_native_estimated_bpa()
    double get_native_pixsize()
    int get_native_map_state()
    float* get_native_vis_phs()

    ############# POLARISATION ######################
    
    const char* get_observation_polarization()

    ###############################

    int l_extract_uv()
    int get_native_uv_count()
    float* get_native_u()
    float* get_native_v()
    float* get_native_vis_amp()
    float* get_native_vis_wgt()
    int* get_native_tel_a()
    int* get_native_tel_b()
    double* get_native_time()
    float* get_native_mod_amp()
    float* get_native_mod_phs()
    int* get_native_subarray()
    const char* get_native_telescope_name(int isub, int itel)
    int* get_native_if()

    # Setters / Actions
    int native_observe(const char* filepath)
    int native_nsub()
    int native_select(const char* pol, int if_beg, int if_end, int ch_beg, int ch_end)
    int native_set_if_range(int if_beg, int if_end)
    int native_get_nif()
    int native_select_ifs(const char* pol, const int* if_list, int n)
    int native_set_if_mask(const int* if_list, int n)
    int native_get_nchan()
    int native_select_channels(const char* pol, const int* bchans, const int* echans, int n_pairs)
    const char *native_get_header_text()
    int native_uvweight(float uvbin, float errpow, int dorad)
    int native_uvtaper(float gauval, float gaurad_wav)
    int native_uvrange(float uvmin_wav, float uvmax_wav)
    int native_uvhwhm(float uvhwhm_pix)
    int native_mapsize(int nx, float cellsize, int ny, float cellsize_y)
    int native_invert()
    int native_clean(int niter, float gain, float cutoff)
    int native_clrmod()
    int native_reset_map_flags()
    int native_refresh_beam()
    int native_restore(int noresid, int dosm)
    int native_restore_beam(float bmaj_mas, float bmin_mas, float bpa_deg, int noresid, int dosm)

    int native_wfits(const char* filename)
    int native_wmap(const char* filename)
    int native_wbeam(const char* filename)
    int native_wdmap(const char* filename)
    int flag_native_data(int *indices, int num_indices)
    int save_native_wobs(const char* filepath)
    int unflag_native_data(int *indices, int num_indices)

    # Statistiques du pic et bruit
    float native_get_peak_flux()
    float native_get_peak_x()
    float native_get_peak_y()
    float native_get_positive_peak_flux()
    float native_get_positive_peak_x()
    float native_get_positive_peak_y()
    float native_get_map_rms()

    # Fenêtres CLEAN
    int native_addwin(float xa, float xb, float ya, float yb)
    int native_delwin()
    int native_peakwin(float size, int doabs)
    int native_get_window_count()
    float native_get_window_xmin(int index)
    float native_get_window_xmax(int index)
    float native_get_window_ymin(int index)
    float native_get_window_ymax(int index)

    # Auto-calibration
    int native_selfcal(int doamp, int dofloat, float solint)
    int native_staper(float gauval, float gaurad_wav)
    int native_set_selfcal_limits(float maxamp, float maxphs)
    int native_set_selfcal_mintel(int p_mintel, int a_mintel)
    int native_set_selfcal_flags(int doflag, int clip)

    # Modèle CLEAN — export des composantes
    int    native_extract_model()
    int    native_get_model_ncmp()
    float* native_get_model_flux()
    float* native_get_model_x()
    float* native_get_model_y()
    float* native_get_model_major()
    float* native_get_model_ratio()
    float* native_get_model_phi()
    int*   native_get_model_type()

    int native_cleanup()
